# Generated by Django 3.0.3 on 2020-07-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminaux_perdus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=36)),
                ('état', models.CharField(max_length=50)),
                ('commentaires', models.CharField(max_length=300)),
                ('identifiant_terminal', models.CharField(max_length=50)),
                ('date_création', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
